spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/BackendExamSys
    username: root
    password: 123456

  devtools:
    restart:
      poll-interval: 1s




